export const SET_ERROR = 'SET_ERROR';
export const GET_PICKUP_ADDRESS = 'GET_PICKUP_ADDRESS';
export const SET_PICKUP_LOCATION = 'SET_PICKUP_LOCATION';
export const SET_DESTINATION = 'SET_DESTINATION';
export const SET_DIRECTIONS = 'SET_DIRECTIONS';

